a

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,11 +1,26 @@
 on: [push]
 
 jobs:
-  job_1:
-    name: Add 3 and 7
+  test:
+    runs-on: ubuntu-latest
+    continue-on-error: ${{ matrix.shouldFail }}
+    strategy:
+      fail-fast: true
+      matrix:
+        shouldFail: [false, false, true, false]
+    steps:
+      - name: Run step
+        run: |
+          echo "Running echo step, shouldFail: ${{ matrix.shouldFail }}"
+          if [ ${{ matrix.shouldFail }} = "true" ]; then
+            echo "Error"
+            exit 1
+          else
+            echo "Success"
+            exit 0
+          fi
+  test2:
     runs-on: ubuntu-latest
     steps:
-      - shell: bash
-        run: |
-          echo ${{github.workspace}} && echo ${{github.event_name}} && echo ${{github.sha}} && echo ${{github.event_name}} && echo ${{github.sha}} && echo ${{github.event_name}} && echo ${{github.sha}} && echo ${{github.event_name}} && echo ${{github.sha}} && echo ${{github.event_name}} && echo ${{github.sha}} && echo ${{github.event_name}} && echo ${{github.sha}} && echo ${{github.event_name}} && echo ${{github.sha}}
-
+      - name: Last step
+        run: echo "Last step"
